version: "3.8"

services:
  buildozer:
    build: .
    container_name: spaceshooter_buildozer
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - TZ=America/Sao_Paulo
    command: buildozer android debug
